# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total_responses',
            field=models.IntegerField(default=0),
        ),
    ]
